ccflags-y += -I$(srctree)/techpack/camera/include/uapi
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_req_mgr

obj-$(CONFIG_SPECTRA_CAMERA) += cam_smmu_api.o
