ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_isp/isp_hw_mgr/include
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += isp_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_isp_dev.o cam_isp_context.o
