ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_smmu
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_cdm
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_lrme
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_lrme/lrme_hw_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus0
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_oneplus/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += cam_lrme_hw_dev.o cam_lrme_hw_core.o cam_lrme_hw_soc.o
